#[localhost]
#127.0.0.1

# ================================================
# Single Node Install (All In One)
# ================================================

[aio]
#opvm001 ansible_host=172.31.250.76 ansible_user=init5
opgap ansible_host=172.31.248.184 ansible_user=init5


# ===============================================
# Multi Node Install (Uncomment Jika Multinode )
# ===============================================

#[controller]
#controller1 ansible_host=172.16.200.15 ansible_user=init5
#controller2 ansible_host=172.16.200.16 ansible_user=init5
#controller3 ansible_host=172.16.200.17 ansible_user=init5

#[compute]
#compute1 ansible_host=172.16.200.15 ansible_user=init5
#compute2 ansible_host=172.16.200.16 ansible_user=init5
#compute3 ansible_host=172.16.200.17 ansible_user=init5

#[storage]
#storage1 ansible_host=172.16.200.15 ansible_user=init5
#storage2 ansible_host=172.16.200.16 ansible_user=init5
#storage3 ansible_host=172.16.200.17 ansible_user=init5


[controller_group:children]
aio
#controller

[compute_group:children]
aio
#compute

[storage_group:children]
aio
#storage
